name: SAST scanning
on:
    push:
      branches: [ "main" ]
      # paths:
      # - '**.cs'
      # - '**.csproj'
    pull_request:
      branches: [ "main" ]
      # paths:
      # - '**.cs'
      # - '**.csproj'
    # schedule:
    # - cron: '0 8 * * 4'
jobs:
  sast-scan:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        languages: ['csharp']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.languages }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
